name = "bliss"
version = "0.1.0"

licences = ["MIT"]
description = "A micro web framework for Gleam"
repository = { type = "github", user = "sporto", repo = "bliss" }

[dependencies]
gleam_stdlib = "~> 0.21"
gleam_http = "~> 3.0"
gleam_elli = "~> 1.1"
gleam_json = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.6"
